/**
 * Record the real pixel size of every photograph a page advertises as its
 * og:image.
 *
 *   node scripts/build-og-dims.mjs
 *
 * Why this has to exist: `og:image:width` and `og:image:height` were emitted
 * as a flat 1200×630 for every page, which is true of the generated OG card
 * and true of nothing else. A suite page advertises its own lead photograph —
 * that is the point, so a shared link shows the right room — and those frames
 * are 3:2, 4:3 and everything in between. Facebook, WhatsApp, Slack and
 * LinkedIn all lay the preview out from the declared numbers before the image
 * itself arrives, so wrong numbers mean a preview that reflows, letterboxes or
 * crops the room out of its own photograph.
 *
 * Declaring nothing would be safe but slower — the scraper then has to fetch
 * and measure. Declaring the truth is both correct and fast, and it costs a
 * generated map of about twenty entries.
 *
 * Only the frames that actually lead a page are measured. Every image on the
 * site would be 439 entries to serve twenty facts.
 */
import { readdirSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";

import sharp from "sharp";

const OUT = "src/content/generated/og-dims.ts";
const PUBLIC = "public";

/* The lead frames: every room's first image, plus the page heroes that pass an
   explicit `image` to pageMetadata. Collected by reading the content rather
   than by listing paths here, so a photograph swap cannot leave a stale size
   behind. */
const { rooms } = await import("../src/content/rooms.ts");

const paths = new Set();
for (const room of rooms) {
  if (room.images[0]) paths.add(room.images[0]);
}

const entries = [];
for (const p of [...paths].sort()) {
  const file = join(PUBLIC, p.replace(/^\//, ""));
  if (!existsSync(file) || !statSync(file).isFile()) {
    console.warn(`  missing, skipped: ${p}`);
    continue;
  }
  const { width, height } = await sharp(file).metadata();
  if (!width || !height) {
    console.warn(`  unreadable, skipped: ${p}`);
    continue;
  }
  entries.push([p, width, height]);
}

const body = entries.map(([p, w, h]) => `  "${p}": [${w}, ${h}],`).join("\n");

writeFileSync(
  OUT,
  `/* GENERATED by scripts/build-og-dims.mjs — do not edit by hand.
   The true pixel size of every photograph a page advertises as its og:image,
   so the declared width and height are the image's own rather than the
   1200×630 of the generated OG card. Re-run after changing a lead frame. */

export const OG_DIMS: Record<string, readonly [number, number]> = {
${body}
};

/** The size of an advertised image, or null when it is not a known frame. */
export function ogDims(src: string): readonly [number, number] | null {
  return OG_DIMS[src] ?? null;
}
`,
  "utf8",
);

console.log(`${OUT}: ${entries.length} frames measured`);
