/**
 * Precompute blur-up placeholders for the photographs that carry a page.
 *
 *   node scripts/build-blur.mjs
 *
 * Next can generate `blurDataURL` itself, but only for statically imported
 * images. Everything here is referenced by path — from `content/`, from the
 * generated maps, from the CMS fallback — so the placeholder has to be built
 * ahead of time and looked up.
 *
 * What it buys: a hero currently paints its scrim over nothing until the
 * photograph decodes, so the first thing a guest sees is a dark rectangle. A
 * 20px blur of the real frame means the page arrives already the right colour
 * and the photograph resolves into it. It is also the difference between a
 * layout that looks loaded and one that looks broken on a hotel-lobby wifi.
 *
 * Deliberately small: 20px wide, quality 40. These are base64 strings inlined
 * into the HTML of every page that shows the image, so the budget is bytes on
 * the critical path, not fidelity — around 400 bytes each. A 64px placeholder
 * looks marginally better and costs four times that, on every request, forever.
 *
 * Only the images that lead a page are built. Blurring all 439 would add
 * ~180 kB of base64 to the bundle to improve tiles nobody waits for.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

import sharp from "sharp";

const OUT = "src/content/generated/blur.ts";

/* ── Which images matter enough to carry a placeholder ─────────────────────
   The hero frames, the plates that fill a viewport, the first photograph of
   every room (its card and its detail hero), and the first screenful of the
   gallery. Everything else is below the fold and lazy. */
async function collect() {
  const wanted = new Set();

  /** Pull "/media/xxx.webp" out of a source file. */
  const fromFile = (path, limitPerMatch = Infinity) => {
    if (!existsSync(path)) return;
    const text = readFileSync(path, "utf8");
    let n = 0;
    for (const m of text.matchAll(/"(\/media\/[a-z0-9]+\.webp)"/g)) {
      if (n >= limitPerMatch) break;
      wanted.add(m[1]);
      n += 1;
    }
  };

  /* Hero and full-bleed plates: every path they name. */
  fromFile("src/components/home/hero.tsx");
  fromFile("src/components/home/the-water.tsx");
  fromFile("src/components/home/the-arrival.tsx");
  fromFile("src/components/home/the-old-town.tsx");
  fromFile("src/components/home/the-open-door.tsx");
  fromFile("src/components/home/the-family.tsx");
  /* Not the feed: six lazy squares at the bottom of the homepage, which is
     already the page carrying the most placeholders. */
  fromFile("src/components/layout/page-hero.tsx");

  /* The lead frame of every room and every generated set. */
  const generated = ["images.ts", "suite-images.ts"];
  for (const g of generated) {
    const path = join("src/content/generated", g);
    if (!existsSync(path)) continue;
    const text = readFileSync(path, "utf8");
    /* First entry of each array only — that is the card and the hero. */
    for (const arr of text.matchAll(/\[\s*\n?\s*"(\/media\/[a-z0-9]+\.webp)"/g)) {
      wanted.add(arr[1]);
    }
  }

  /* NOT the gallery. Measured: inlining twelve placeholders there took
     /gallery from 88 to 84 and its LCP from 3.6 s to 4.6 s. The tiles are
     lazy thumbnails in a masonry column — nobody waits on one, and the
     base64 lands in the HTML of the single page that already carries the
     most images. A blur-up is worth bytes only where the reader is staring
     at the space while it loads. */

  return [...wanted].filter(Boolean);
}

const paths = await collect();
console.log(`building placeholders for ${paths.length} images`);

const entries = [];
let skipped = 0;

for (const webPath of paths) {
  const file = join("public", webPath);
  if (!existsSync(file)) {
    skipped += 1;
    continue;
  }
  try {
    const buf = await sharp(file)
      .resize(20, null, { fit: "inside" })
      .webp({ quality: 40 })
      .toBuffer();
    entries.push([webPath, `data:image/webp;base64,${buf.toString("base64")}`]);
  } catch (err) {
    console.warn(`  skipped ${webPath}: ${err.message}`);
    skipped += 1;
  }
}

entries.sort((a, b) => a[0].localeCompare(b[0]));

const bytes = entries.reduce((n, [, v]) => n + v.length, 0);

writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/build-blur.mjs. Do not edit by hand.
//
// A 20px WebP of each photograph that leads a page, inlined so the page
// arrives the right colour instead of painting a scrim over nothing while the
// real frame decodes.
//
// ${entries.length} placeholders, ${(bytes / 1024).toFixed(1)} kB of base64 in total.
// Only images that lead a page are here; blurring all 439 would add roughly
// 180 kB to improve tiles nobody waits for.

export const BLUR: Readonly<Record<string, string>> = {
${entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n")}
};

/** The placeholder for an image, if one was built. */
export function blurFor(src: string | undefined | null): string | undefined {
  return src ? BLUR[src] : undefined;
}
`,
);

console.log(
  `wrote ${OUT} — ${entries.length} placeholders, ${(bytes / 1024).toFixed(1)} kB` +
    (skipped ? `, ${skipped} skipped` : ""),
);
