/**
 * The photo intake. One folder, one command.
 *
 *   1. drop files into  incoming/
 *   2. run             npm run photos
 *
 * Everything between those two steps is here, in order, and each step is the
 * script that already owned that job — this does not reimplement them, it
 * runs them in the order that makes them correct:
 *
 *   ingest        every file in incoming/ becomes a right-sized .webp in
 *                 public/media, named after itself rather than after a hash,
 *                 and the original moves to incoming/_processed
 *   register      src/content/generated/intake.ts records each new frame with
 *                 its size and an empty alt slot per locale
 *   blur          build-blur.mjs, so anything that leads a page has a
 *                 placeholder
 *   og            build-og-dims.mjs, so a shared link declares the real size
 *   verify        check-media.mjs, which fails on a missing file or a quality
 *                 the config does not allow
 *   manifest      media-manifest.mjs, which records what is referenced and
 *                 prints the ignore lines for what is not
 *
 * Then it prints what is still owed: every frame with no alt text, and every
 * frame nothing references yet. Both are normal on the day photographs
 * arrive — they are work, not errors, and the command says so rather than
 * failing.
 *
 * Flags:
 *   --dry     ingest nothing, just say what would happen
 *   --report  skip ingest, print what is owed (this is `npm run photos:check`)
 */
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const INCOMING = path.join(ROOT, "incoming");
const PROCESSED = path.join(INCOMING, "_processed");
const MEDIA = path.join(ROOT, "public", "media");
const INTAKE_TS = path.join(ROOT, "src", "content", "generated", "intake.ts");

/* The same numbers optimise-media.mjs uses on the mirrored library. A frame
   that arrives today should not be bigger than the ones already here. */
const MAX_EDGE = 2400;
const QUALITY = 82;

const LOCALES = ["en", "el", "de", "fr", "nl"];
const DRY = process.argv.includes("--dry");
const REPORT_ONLY = process.argv.includes("--report");

const say = (s = "") => console.log(s);

/** photograph-of-the-courtyard.HEIC → photograph-of-the-courtyard */
function slugify(name) {
  return path
    .basename(name, path.extname(name))
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")   // combining marks, spelled out
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "photo";
}

/** Never overwrite a frame that is already here. */
function freeName(slug) {
  let name = `${slug}.webp`;
  let n = 2;
  while (fs.existsSync(path.join(MEDIA, name))) {
    name = `${slug}-${n++}.webp`;
  }
  return name;
}

function readIntake() {
  if (!fs.existsSync(INTAKE_TS)) return [];
  const src = fs.readFileSync(INTAKE_TS, "utf8");
  const json = /const ENTRIES = (\[[\s\S]*?\]) as const;/.exec(src)?.[1];
  if (!json) return [];
  try {
    return JSON.parse(json);
  } catch {
    return [];
  }
}

function writeIntake(entries) {
  const body = `// AUTO-GENERATED by scripts/photos.mjs. Do not edit by hand.
//
// Every photograph that came in through incoming/, with the alt text it still
// owes. \`alt\` holds one slot per locale; null means nobody has written it
// yet, and a frame with a null slot must not lead a page — a photograph
// nobody can hear is a photograph half the readers do not get.
//
// Fill the English slot first, then the other four. \`npm run photos:check\`
// lists what is outstanding.

export interface IntakePhoto {
  /** The path as the site references it. */
  readonly file: string;
  /** What the file was called when it arrived, kept for provenance. */
  readonly original: string;
  readonly width: number;
  readonly height: number;
  readonly bytes: number;
  /** ISO date of intake. */
  readonly added: string;
  readonly alt: Readonly<Record<string, string | null>>;
}

const ENTRIES = ${JSON.stringify(entries, null, 2)} as const;

export const intakePhotos: readonly IntakePhoto[] = ENTRIES;

/** The frames still owed alt text, in the locales that owe it. */
export function missingAlt(): { file: string; locales: string[] }[] {
  return intakePhotos
    .map((p) => ({
      file: p.file,
      locales: Object.entries(p.alt)
        .filter(([, v]) => !v)
        .map(([l]) => l),
    }))
    .filter((r) => r.locales.length > 0);
}
`;
  fs.writeFileSync(INTAKE_TS, body, "utf8");
}

/** Every /media/… path the site mentions, so we can say what is unused. */
function referencedPaths() {
  const roots = ["src", "sanity"].map((d) => path.join(ROOT, d));
  const found = new Set();
  const walk = (dir) => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else if (/\.(tsx?|mjs|json)$/.test(e.name)) {
        const text = fs.readFileSync(p, "utf8");
        /* The generated intake file names every frame by definition; counting
           it as a reference would mean nothing is ever reported unused. */
        if (p === INTAKE_TS) continue;
        for (const m of text.matchAll(/\/media\/[A-Za-z0-9._-]+/g)) found.add(m[0]);
      }
    }
  };
  for (const r of roots) if (fs.existsSync(r)) walk(r);
  return found;
}

/**
 * Run one of the existing scripts.
 *
 * `tsx: true` for the ones that import the site's TypeScript — build-og-dims
 * reads the content files to learn which frame each page advertises, and
 * plain node cannot load those.
 */
function run(label, file, { tsx = false } = {}) {
  say(`\n── ${label} ${"─".repeat(Math.max(0, 58 - label.length))}`);
  const args = tsx
    ? ["--import", "tsx", path.join("scripts", file)]
    : [path.join("scripts", file)];
  try {
    execFileSync(process.execPath, args, { stdio: "inherit" });
    return true;
  } catch {
    say(`\n${label} failed. Nothing after it has run.`);
    return false;
  }
}

// ── ingest ──────────────────────────────────────────────────────────────────
let entries = readIntake();
const arrived = [];

if (!REPORT_ONLY) {
  if (!fs.existsSync(INCOMING)) {
    fs.mkdirSync(INCOMING, { recursive: true });
    say(`Created ${path.relative(ROOT, INCOMING)}. Drop photographs in it and run this again.`);
  }

  const files = fs
    .readdirSync(INCOMING, { withFileTypes: true })
    .filter((e) => e.isFile() && /\.(jpe?g|png|webp|tiff?|avif)$/i.test(e.name))
    .map((e) => e.name);

  if (!files.length) {
    say(`Nothing in ${path.relative(ROOT, INCOMING)}/ — going straight to the report.`);
  }

  for (const f of files) {
    const from = path.join(INCOMING, f);
    const name = freeName(slugify(f));
    const to = path.join(MEDIA, name);

    const meta = await sharp(from).metadata();
    const long = Math.max(meta.width ?? 0, meta.height ?? 0);

    if (DRY) {
      say(`would write  public/media/${name}  (${meta.width}×${meta.height}${long > MAX_EDGE ? ` → long edge ${MAX_EDGE}` : ""})`);
      continue;
    }

    const pipeline = sharp(from).rotate();
    if (long > MAX_EDGE) {
      pipeline.resize({
        width: meta.width >= meta.height ? MAX_EDGE : undefined,
        height: meta.height > meta.width ? MAX_EDGE : undefined,
        withoutEnlargement: true,
      });
    }
    await pipeline.webp({ quality: QUALITY }).toFile(to);

    const out = await sharp(to).metadata();
    const bytes = fs.statSync(to).size;

    fs.mkdirSync(PROCESSED, { recursive: true });
    fs.renameSync(from, path.join(PROCESSED, f));

    const entry = {
      file: `/media/${name}`,
      original: f,
      width: out.width ?? 0,
      height: out.height ?? 0,
      bytes,
      added: new Date().toISOString().slice(0, 10),
      alt: Object.fromEntries(LOCALES.map((l) => [l, null])),
    };
    entries = entries.filter((e) => e.file !== entry.file).concat(entry);
    arrived.push(entry);

    say(
      `${f}  →  public/media/${name}  ${out.width}×${out.height}, ${(bytes / 1024).toFixed(0)} kB`,
    );
  }

  if (arrived.length && !DRY) writeIntake(entries);
}

// ── the chain ───────────────────────────────────────────────────────────────
if (!DRY && !REPORT_ONLY) {
  const chain = [
    ["Blur placeholders", "build-blur.mjs", {}],
    ["Open Graph dimensions", "build-og-dims.mjs", { tsx: true }],
    ["Media — references resolve, qualities declared", "check-media.mjs", {}],
    ["Manifest — what is referenced, what is not", "media-manifest.mjs", {}],
  ];
  for (const [label, file, opts] of chain) {
    if (!run(label, file, opts)) {
      process.exitCode = 1;
      break;
    }
  }
}

// ── what is still owed ──────────────────────────────────────────────────────
entries = readIntake();
const referenced = referencedPaths();

say(`\n── Still owed ${"─".repeat(48)}`);

const noAlt = entries
  .map((e) => ({ file: e.file, locales: LOCALES.filter((l) => !e.alt?.[l]) }))
  .filter((r) => r.locales.length);

if (!entries.length) {
  say("No photographs have come through intake yet.");
} else {
  if (noAlt.length) {
    say(`${noAlt.length} frame(s) still need alt text:`);
    for (const r of noAlt) say(`  ${r.file}  — ${r.locales.join(", ")}`);
    say("\nWrite it in src/content/generated/intake.ts, English first.");
  } else {
    say("Every intake frame has alt text in all five languages.");
  }

  const unused = entries.filter((e) => !referenced.has(e.file));
  if (unused.length) {
    say(`\n${unused.length} frame(s) are on disk but nothing references them yet:`);
    for (const e of unused) say(`  ${e.file}`);
    say("\nReference them from src/content/, then run this again.");
  }

  /* The one condition that is an error rather than a to-do: a frame that is
     live on the site with nobody able to hear it. */
  const liveAndMute = noAlt.filter((r) => referenced.has(r.file));
  if (liveAndMute.length) {
    say(`\n${liveAndMute.length} frame(s) are referenced by the site with no alt text:`);
    for (const r of liveAndMute) say(`  ${r.file}  — ${r.locales.join(", ")}`);
    say("\nThat one is an error, not a to-do. A published photograph says something.");
    process.exitCode = 1;
  }
}

say("");
